### ISSUE TITLE
Local host of site unavailable

### ISSUE THREAD

**Issue by jamesonhill** [taylonr/intro-to-protractor#6]
Is there anything wrong with your site? Whenever I go to http://localhost:3000/#!/EventRatings is says 'The site cannot be reached'. Am I not going about it the correct way?

**Comment by taylonr** [comment]
Not that I'm aware of. Are you getting any errors in the terminal when you run `grunt`?

**Comment by jamesonhill** [comment]
Yes.

Jameson Hill@DESKTOP-GP6CRIB MINGW64 ~/desktop/protractor-tutorial/intro-to-protractor/protractor/ratings (master)
$ grunt
Loading "grunt-karma.js" tasks...ERROR
>> TypeError: Cannot read property 'prototype' of undefined
>> Local Npm module "grunt-node-inspector" not found. Is it installed?

Running "jshint:all" (jshint) task
Warning: Path must be a string. Received null Used --force, continuing.

Running "csslint:all" (csslint) task
>> 3 files lint free.

Running "concurrent:default" (concurrent) task
Loading "grunt-karma.js" tasks...ERROR
Loading "grunt-karma.js" tasks...>> TypeError: Cannot read property 'prototype' of undefined
ERROR
>> TypeError: Cannot read property 'prototype' of undefined
>> Local Npm module "grunt-node-inspector" not found. Is it installed?
>> Local Npm module "grunt-node-inspector" not found. Is it installed?

Running "nodemon:dev" (nodemon) task

Running "watch" task
Waiting...
[nodemon] v1.0.20
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: app/views/**/*.* gruntfile.js server.js config/**/*.js app/**/*.js
[nodemon] starting `node --debug server.js`
(node:13652) DeprecationWarning: node --debug is deprecated. Please use node --inspect instead.
Debugger listening on 127.0.0.1:5858

 NODE_ENV is not defined! Using default development environment

{ Error: Cannot find module '../build/Release/bson'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Jameson Hill\desktop\protractor-tutorial\intro-to-protractor\node_modules\bson\ext\index.js:15:10)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3) code: 'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version
MEAN.JS application started on port 3000
events.js:163
      throw er; // Unhandled 'error' event
      ^

Error: failed to connect to [localhost:27017]
    at exports.ConnectionPool.<anonymous> (C:\Users\Jameson Hill\desktop\protractor-tutorial\intro-to-protractor\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\server.js:556:25)
    at emitThree (events.js:116:13)
    at exports.ConnectionPool.emit (events.js:197:7)
    at exports.Connection.<anonymous> (C:\Users\Jameson Hill\desktop\protractor-tutorial\intro-to-protractor\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection_pool.js:156:15)
    at emitTwo (events.js:106:13)
    at exports.Connection.emit (events.js:194:7)
    at Socket.<anonymous> (C:\Users\Jameson Hill\desktop\protractor-tutorial\intro-to-protractor\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection.js:534:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at emitErrorNT (net.js:1284:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
[nodemon] app crashed - waiting for file changes before starting...
